ShintaApp/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

app_name = 'ShintaApp'

urlpatterns = [
	path('', index, name="index"),
    path('login/', loginpage, name="loginpage"),
    path('logout/', logout, name="logout"),
    path('register/', register, name="register"),

   

]

TK2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShintaApp.urls')),
]

ShintaApp/models.py
from django.db import models

# Create your models here.


class Account(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

ShintaApp/forms.py
from django import forms
from .models import Account


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(max_length=100, required=True)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    email = forms.EmailField()
    password = forms.CharField(max_length=100, required=True)

ShintaApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .models import Account
from .forms import LoginForm, RegisterForm

# Create your views here.

# Create your views here.
def index (request):
	return render (request,"masigatau.html")
def register(request):
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            if (authenticate(username=request.POST['username'], email=request.POST['email'], password=request.POST['password'])) is None:
                user = User.objects.create_user(
                    request.POST['username'], request.POST['email'], request.POST['password'])
                user.save()
                auth_login(request, user)
                return redirect('/')
            else:
                return render(request,"masigatau.html")
    
def loginpage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.filter(username=username).exists()
        if user:
            is_authenticate = authenticate(
                username=username, password=password)
            if is_authenticate:
                auth_login(request, is_authenticate)
                return redirect('/')
            else:
                print('error_password')
        else:
            print('error_user')
    return render(request, 'masigatau.html')
    
@login_required
def logout(request):
    auth_logout(request)
    return redirect('/')

ShintaApp/templates/masigatau.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title> ThriftYuk </title>
{% endblock %}
 
{% block content %}
<section id="home1">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'assets/slidesatu.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'assets/slide2.jpg' %}" alt="Second slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section id="home2" class="text-center" style="background-color: #FFEBCD">
    <div class="container">
        <div class="row">
             <div class="col-lg-4">
                 <h1 style="margin-top: 50% ; margin-bottom: 30%; font-size: 3.2em"> ResepPisan </h1>
            </div>
            <div class="col-lg-8">
                <div style="margin-top: 18% ;margin-bottom: 18% ;font-size: 22px;"> Situs ini menyajikan informasi terlengkap mengenai segala hal tentang dunia masak-memasak. Kami berusaha menyajikan langkah-langkah yang mudah dipahami dan praktis, untuk membantu meringankan pekerjaan Anda di dapur. Cocok untuk pemula yang sedang belajar masak, maupun yang sudah mahir namun sering bingung mau masak apa.</div>
            </div>
        </div>
    </div>
</section>
<section id="home3" style="margin-top: 12%; margin-bottom: 12%">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="text-center" style="background-color: #FFF8DC; padding: 10px">
                    <h2 style="margin-top: 10%"> Tips and Trick </h2>
                    <div> Ada banyak tips yang jarang terpikirkan oleh Anda. Lihat beberapa tips berikut yang dapat membantu pekerjaan dapur jadi lebih mudah dan cepat.</div>
                    <button style="margin-top: 35px; margin-bottom: 15px; border-radius: 5px"> Lihat Tips</button>
                </div>
            </div>
            <div class="col-sm-4">
                    <div class="text-center" style="background-color: #B0E0E6; padding: 10px">
                        <h2 style="margin-top: 10%"> Informasi Gizi </h2>
                        <div> Mengonsumsi ragam makanan dalam satu porsi, bukan berarti telah mencukupi segala nutrisi. Ada baiknya Anda tahu makanan apa saja yang memiliki kandungan nutrisi sama. </div>
                        <button style="margin-top: 35px; margin-bottom: 15px; border-radius: 5px"> Lihat Info Gizi </button>
                    </div>
                </div>
            <div class="col-sm-4">
                <div class="text-center" style="background-color: #D8BFD8; padding: 10px">
                    <h2 style="margin-top: 10%"> Top Kuliner Depok </h2>
                    <div> Apa yang terpikirkan di kepala anda ketika mendengar kata Depok? Universitas Indonesia? sayangnya Depok tidak hanya tentang itu. Depok memiliki beberapa tempat kuliner yang tak kalah menarik</div>
                    <button style="margin-top: 15px; margin-bottom: 15px; border-radius: 5px"> Lihat Tempat </button>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="home4"  style="background-color: #CD853F">
    <div class="container">
        <div class="row">
                <div style="margin-top: 30px; margin-bottom: 30px"></div>
            </div>
        </div>
    </div>
</section>
  
     
 

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE>
<html>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	{% block styles %}{% endblock %}

<body>
	<nav class="navbar-fixed navbar-expand-md navbar-light " style="background-color: #CD853F;">
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
 	  </button>
  	<div class="collapse navbar-collapse" id="navbarNavDropdown" >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="navbar-brand" href="/"; style="font-size: 20px ; color : white; font-weight: bold ;padding: 10px"> ResepPisan </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" style="font-size: 20px ; color : white;font-weight: bold; padding: 10px"> Fitur 1 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" style="font-size: 20px; color : white; font-weight: bold; padding: 10px"> Fitur 2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" style="font-size: 20px ; color : white; font-weight: bold; padding: 10px"> Fitur 3</a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a href="/logout/"><button style="font-size: 20px ; color : black; "> Logout </button></a>
          {% else %}
          <li class="nav-item">
           <button style="font-size: 20px ; color : black; " data-toggle="modal" data-target="#signupModal"> Sign Up </button></a>
              <div class = "modal fade" role="dialog" id="signupModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type ="button" class = "close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class = "modal-body">
                          {% if user.is_authenticated %}
                          <h1 class="px-5 pt-5">Hi {{ user.username }}, you're already registered.</h1>
                          <a href="/" class="px-5">Back to homepage</a>
                          {% else %}
                          <form method="POST" action="/register/">
                            {% csrf_token %}
                            <table class="table">
                              <tr>
                                <td><label for="id_username" id="labeluname">Username</label></td>
                                <td><input id="id_username"name="username" type="text" class="form-control"></td>
                              </tr>
                              <tr>
                                <td><label for="id_email">Email</label></td>
                                <td><input id="id_email" name="email" type="email" class="form-control" required></td>
                              </tr>
                              <tr>
                                <td><label for="id_password" id ="labelpw">Password</label></td>
                                <td><input id="id_password" name="password" type="password" class="form-control"></td>
                              </tr>
                            </table>
                            <div class="modal-footer">
                            <input type="submit" class="btn btn-success" value="Register">
                          </div>
                          </form>
                         <div class="text-center">
                            <p>Already have an account?</p>
                            <a href="/login/">Login here</a>
                            {% endif %}
                        </div>
                   </div>
              </li>

            <li class="nav-item">
                <button style="font-size: 20px ; color : black" data-toggle="modal" data-target="#loginModal"> Login </button></a>
                <div class = "modal fade" role="dialog" id="loginModal">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type ="button" class = "close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class = "modal-body">
                      <form action="/login/" class="form-popup" id="myForm" method="post">
                      {% csrf_token %}
                      <table class="table">
                        <tr>
                            <td><label for="id_username" id="labeluname">Username</label></td>
                            <td><input id="id_username"name="username" type="text" class="form-control"></td>
                        </tr>
                        <tr>
                            <td><label for="id_password" id ="labelpw">Password</label></td>
                            <td><input id="id_password" name="password" type="password" class="form-control"></td>
                        </tr>
                      </table>
                      {% if form.errors %}
                      <p class=" label label-danger">Username kamu salah, silahkan coba lagi.</p>
                      {% endif %}
                      <div class="modal-footer">
                      <input type="submit"  value="Login" class="btn btn-success">
                      <input type="hidden" name="next" value="{{ next }}">
                      </form>
                      </div>
              </li>
             {% endif %}
        </ul>
    </div>
</nav>
  {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  	{% block scripts %}{% endblock %}
</body>